---
#
# Automations in Home Assistant allow you to automatically respond to things that happen. 
# You can turn the lights on at sunset or pause the music when you receive a call.
# https://www.home-assistant.io/docs/automation/
#
# This handles the loading of my automations

## Listing the automations in the automations folder
automation: !include_dir_list ../automations

## added to be able to use the included automation editor
automation editor: !include ../automations.yaml