---
# Sensors are a basic platform component in Home Assistant. 
# They monitor the states and conditions of a variety of entities. An entity can be many things. 
# This can include a physical device like a motion sensor that reports the battery level, 
# a web service that retrieves the weather temperature, 
# a built-in function that calculates the sun’s elevation relative to your GPS position, 
# or even a custom sensor you may have created to report the free space on your laptop. 
# These are all things reporting different types of information.
#
# This loads up my sensor configurations
#
# https://www.home-assistant.io/components/sensor/
#

## Listing the binary sensors.
binary_sensor: !include_dir_list ../entities/binary_sensors
