- id: '1613302275852'
  alias: Albertheijn
  description: Locatie test
  trigger:
  - platform: zone
    entity_id: person.michel_vrauwdeunt
    zone: zone.albert_heijn_rozenburg
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Click to open the shopping list
      title: Boodschappenlijst
      data:
        clickAction: /shopping-list
        url: /shopping-list
  mode: single
- id: '1615584209554'
  alias: 3D Printer klaar met printen.
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ender_3_printing
    from: 'on'
    to: 'off'
    for: 1 seconde
  condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Printer is klaar met printen
      title: Ender 3
  mode: single
- id: '1615618158397'
  alias: Printer verbonden
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ender_3_current_state
    from: unknown
    to: Operational
  condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Ender 3 staat klaar
      message: 3D printer is verbonden met OctoPrint
  mode: single
- id: '1620548369947'
  alias: Home Assistant Update Notification for Android
  description: ''
  use_blueprint:
    path: update-notifier-for-android.yaml
    input:
      clickAction: https://hass.gladsheimr.nl/config/info
      delay: 0
      notify_device: e775efe73342b7e445bd2d8482b2b198
      group: Available Updates
- id: '1620911662728'
  alias: Werkpc aan zetten
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.werken
    from: 'False'
    to: 'True'
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Tijd om te werken
      message: Maak je klaar om te gaan werken
  mode: single
- id: '1621408726454'
  alias: Deconz niet beschikbaar
  description: ''
  trigger:
  - platform: state
    entity_id: light.hal
    to: unavailable
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Deconz werkt niet
      message: Deconz is niet beschikbaar. is het ip adres verandert?
  mode: single
