- id: '1613302275852'
  alias: Albertheijn
  description: Locatie test
  trigger:
  - platform: zone
    entity_id: person.michel_vrauwdeunt
    zone: zone.albert_heijn_rozenburg
    event: enter
  condition:
  - condition: numeric_state
    entity_id: sensor.shopping_list
    above: '0'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Klik hier voor de boodschappenlijst
      title: Boodschappenlijst
      data:
        clickAction: /shopping-list
        url: /shopping-list
  mode: single
- id: '1615584209554'
  alias: 3D Printer klaar met printen.
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ender_3_printing
    from: 'on'
    to: 'off'
    for: 1 seconde
  condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Printer is klaar met printen
      title: Ender 3
  mode: single
- id: '1615618158397'
  alias: Printer verbonden
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ender_3_current_state
    from: unknown
    to: Operational
  condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Ender 3 staat klaar
      message: 3D printer is verbonden met OctoPrint
  mode: single
- id: '1620548369947'
  alias: Home Assistant Update Notification for Android
  description: ''
  use_blueprint:
    path: update-notifier-for-android.yaml
    input:
      clickAction: https://hass.gladsheimr.nl/config/info
      delay: 0
      notify_device: e775efe73342b7e445bd2d8482b2b198
      group: Available Updates
- id: '1620911662728'
  alias: Werkpc aan zetten
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.werken
    from: 'False'
    to: 'True'
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Tijd om te werken
      message: Maak je klaar om te gaan werken
  mode: single
- id: '1621408726454'
  alias: Deconz niet beschikbaar
  description: ''
  trigger:
  - platform: state
    entity_id: light.hal
    to: unavailable
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Deconz werkt niet
      message: Deconz is niet beschikbaar. is het ip adres verandert?
  mode: single
- id: '1621680846116'
  alias: Eurovision Songfestival
  description: ''
  trigger:
  - platform: time
    at: '20:55'
  condition:
  - condition: template
    value_template: '{{ now().date() == "2021-05-22" }}'
  action:
  - service: light.turn_on
    target:
      entity_id: light.ambilight
    data:
      effect: Italie finland
  mode: single
- id: '1621681800474'
  alias: Eurovision Songfestival (Dupliceren)
  description: ''
  trigger:
  - platform: time
    at: 0:45
  condition:
  - condition: template
    value_template: '{{ now().date() == "2021-05-23" }}'
  - condition: state
    entity_id: switch.sleeping
    state: 'Off'
  action:
  - service: light.turn_on
    target:
      entity_id: light.ambilight
    data:
      effect: Kaars2
  mode: single
- id: '1622024793389'
  alias: Dog test
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_sensor_pir_sensor
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: media_player.volume_set
    target:
      entity_id: media_player.wallpanel
    data:
      volume_level: 1
  - service: media_player.play_media
    data:
      media_content_id: /local/sounds/Dog2.mp3
      media_content_type: mp3
    target:
      entity_id: media_player.wallpanel
  mode: single
- id: '1622671459948'
  alias: Regen melding
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.neerslag_buienalarm_regen_data
    above: '1'
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Het gaat regenen
      title: Regen
  mode: single
- id: '1623156285450'
  alias: Poekie eten gegeven
  description: Feed the cat
  trigger:
  - platform: time
    at: '20:00'
  condition: []
  action:
  - service: grocy.consume_product_from_stock
    data:
      product_id: 93
      amount: 1
  mode: single
- id: '1623157040847'
  alias: Poekie eten bijna op
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kattenvoer
    below: '5'
  condition:
  - condition: template
    value_template: '{%- set list = state_attr(''sensor.shopping_list'', ''boodschappen'')
      | lower %}

      {{ ''kattenvoer'' not in list }}'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Oh no poekie zit bijna zonder eten
      title: 'Poekie '
  - service: shopping_list.add_item
    data:
      name: Kattenvoer
  mode: single
- id: '1623414912233'
  alias: Recipe select step
  description: Select steps
  trigger:
  - platform: event
    event_type: rhasspy_HassRecipeSelectStep
    event_data: {}
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Stap {{ trigger.event.data.number | string }}
      message: '{%- set i = "step_" + trigger.event.data.number | string %} {{state_attr(''sensor.cooking'',i)|replace("''","")|replace("[","")|replace("]","")}}'
  - service: python_script.set_state
    data_template:
      entity_id: input_number.recipe_step
      state: '{{trigger.event.data.number| int }}'
  mode: single
- id: '1623505526163'
  alias: Recipe Last step
  description: Send next step
  trigger:
  - platform: event
    event_type: rhasspy_HassRecipeStep
    event_data:
      modifier: vorige
  condition:
  - condition: template
    value_template: "{%- set w = states('input_number.recipe_step')|int - 1 %}\n{%-\
      \ set i = \"step_\" + w|string %}  \n{{ state_attr('sensor.cooking', i) != None\
      \ }}"
  action:
  - service: input_number.decrement
    target:
      entity_id: input_number.recipe_step
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Stap {{ states('input_number.recipe_step').split('.')[0] }}
      message: '{%- set i = "step_" + states(''input_number.recipe_step'').split(''.'')[0]
        %} {{state_attr(''sensor.cooking'',i)|replace("''","")|replace("[","")|replace("]","")}}'
  mode: single
- id: '1623505894399'
  alias: Recipe curent step
  description: Send current step
  trigger:
  - platform: event
    event_type: rhasspy_HassRecipeStep
    event_data:
      modifier: huidige
  condition:
  - condition: numeric_state
    entity_id: input_number.recipe_step
    above: '0'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Stap {{ states('input_number.recipe_step').split('.')[0] }}
      message: '{%- set i = "step_" + states(''input_number.recipe_step'').split(''.'')[0]
        %}  {%- set message = state_attr(''sensor.cooking'', i) %} {%- if message
        != None%} {{ message }} {% endif %}'
  mode: single
- id: '1623523159083'
  alias: Recipe clear step
  description: ''
  trigger:
  - platform: template
    value_template: "{%- set w = states('input_number.recipe_step')|int + 1 %}\n{%-\
      \ set i = \"step_\" + w|string %} \n{{ state_attr('sensor.cooking', i) == None\
      \ }}"
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.recipe_step
    data:
      value: 0
  mode: single
- id: '1623526529325'
  alias: Recipe next step
  description: Send next step
  trigger:
  - platform: event
    event_type: rhasspy_HassRecipeStep
    event_data:
      modifier: volgende
  condition:
  - condition: template
    value_template: "{%- set w = states('input_number.recipe_step')|int + 1 %}\n{%-\
      \ set i = \"step_\" + w|string %}  \n{{ state_attr('sensor.cooking', i) != None\
      \ }}"
  action:
  - service: input_number.increment
    target:
      entity_id: input_number.recipe_step
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Stap {{ states('input_number.recipe_step').split('.')[0] }}
      message: '{%- set i = "step_" + states(''input_number.recipe_step'').split(''.'')[0]
        %} {{state_attr(''sensor.cooking'',i)|replace("''","")|replace("[","")|replace("]","")}}'
  mode: single
- id: '1623606798603'
  alias: Recipe select recipe
  description: Select recept
  trigger:
  - platform: event
    event_type: rhasspy_HassRecipeSelect
    event_data: {}
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Recept geselecteerd
      message: '{%- set w = trigger.event.data.recept| int %} {%- set recept = state_attr(''sensor.recipies'',
        ''recepten'') %} {%- for i in recept %} {%- if w == i.id|int %} {{ i.name
        }} {%- endif %} {%- endfor %}'
  - service: python_script.set_state
    data_template:
      entity_id: input_number.recipe_id
      state: '{%- set w = trigger.event.data.recept| int %} {%- set recept = state_attr(''sensor.recipies'',
        ''recepten'') %} {%- for i in recept %} {%- if w == i.id|int %}  {{ loop.index-1
        }} {%- endif %} {%- endfor %}'
  mode: single
- id: '1623618935950'
  alias: shopping_list_test
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.grocy_shopping_list
    above: '0'
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: '{{ trigger.state }}'
  - condition: template
    value_template: '{%- set hs = state_attr(''sensor.shopping_list'', ''boodschappen'')
      %}

      {%- set gc = state_attr(''sensor.grocy_shopping_list'', ''products'') %}

      {%- for product in gc %}

      {%- set test = product.product.name %}

      {{ test|lower not in hs|lower }}

      {%- endfor %}'
  mode: single
- id: '1627474269057'
  alias: Ambilight Capture on
  description: ''
  trigger:
  - platform: template
    value_template: '{{ is_state_attr(''media_player.baldr'', ''media_content_type'',
      ''tvshow'') }}'
    id: serie playing
  - platform: template
    value_template: '{{ is_state_attr(''media_player.baldr'', ''media_content_type'',
      ''movie'') }}'
    id: movie playing
  condition:
  - condition: numeric_state
    entity_id: sensor.woonkamer_sensor_illuminance
    below: '15'
  action:
  - service: light.turn_on
    target:
      entity_id: light.ambilight
    data:
      effect: Platform Capture
  mode: single
- id: '1627476676939'
  alias: Ambilight Capture off
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.baldr
    id: idle
    to: idle
  - platform: state
    entity_id: media_player.baldr
    id: paused
    from: playing
    to: paused
    for: 0:05:00
  - platform: template
    value_template: '{{ is_state_attr(''media_player.baldr'', ''media_content_type'',
      ''music'') }}'
    id: music playing
  - platform: numeric_state
    entity_id: sensor.woonkamer_sensor_illuminance
    above: '20'
  condition: []
  action:
  - condition: numeric_state
    entity_id: sensor.woonkamer_sensor_illuminance
    below: '15'
  - service: light.turn_on
    target:
      entity_id: light.ambilight
    data:
      effect: Kaars2
  - condition: numeric_state
    entity_id: sensor.woonkamer_sensor_illuminance
    above: '15'
  - service: light.turn_on
    target:
      entity_id: light.ambilight
    data:
      effect: Kaars2
  - service: light.turn_off
    target:
      entity_id: light.ambilight
  mode: single
