- id: '1613302275852'
  alias: Albertheijn
  description: Locatie test
  trigger:
  - platform: zone
    entity_id: person.michel_vrauwdeunt
    zone: zone.albert_heijn_rozenburg
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Click to open the shopping list
      title: Boodschappenlijst
      data:
        clickAction: /shopping-list
        url: /shopping-list
  mode: single
- id: '1615584209554'
  alias: 3D Printer klaar met printen.
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ender_3_printing
    from: 'on'
    to: 'off'
    for: 1 seconde
  condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Printer is klaar met printen
      title: Ender 3
  mode: single
- id: '1615618158397'
  alias: Printer verbonden
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ender_3_current_state
    from: unknown
    to: Operational
  condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Ender 3 staat klaar
      message: 3D printer is verbonden met OctoPrint
  mode: single
- id: '1620548369947'
  alias: Home Assistant Update Notification for Android
  description: ''
  use_blueprint:
    path: update-notifier-for-android.yaml
    input:
      clickAction: https://hass.gladsheimr.nl/config/info
      delay: 0
      notify_device: e775efe73342b7e445bd2d8482b2b198
      group: Available Updates
- id: '1620911662728'
  alias: Werkpc aan zetten
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.werken
    from: 'False'
    to: 'True'
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Tijd om te werken
      message: Maak je klaar om te gaan werken
  mode: single
- id: '1621408726454'
  alias: Deconz niet beschikbaar
  description: ''
  trigger:
  - platform: state
    entity_id: light.hal
    to: unavailable
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Deconz werkt niet
      message: Deconz is niet beschikbaar. is het ip adres verandert?
  mode: single
- id: '1621680846116'
  alias: Eurovision Songfestival
  description: ''
  trigger:
  - platform: time
    at: '20:55'
  condition:
  - condition: template
    value_template: '{{ now().date() == "2021-05-22" }}'
  action:
  - service: light.turn_on
    target:
      entity_id: light.ambilight
    data:
      effect: Italie finland
  mode: single
- id: '1621681800474'
  alias: Eurovision Songfestival (Dupliceren)
  description: ''
  trigger:
  - platform: time
    at: 0:45
  condition:
  - condition: template
    value_template: '{{ now().date() == "2021-05-23" }}'
  - condition: state
    entity_id: switch.sleeping
    state: 'Off'
  action:
  - service: light.turn_on
    target:
      entity_id: light.ambilight
    data:
      effect: Kaars2
  mode: single
- id: '1622024793389'
  alias: Dog test
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_sensor_pir_sensor
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: media_player.volume_set
    target:
      entity_id: media_player.wallpanel
    data:
      volume_level: 1
  - service: media_player.play_media
    data:
      media_content_id: /local/sounds/Dog2.mp3
      media_content_type: mp3
    target:
      entity_id: media_player.wallpanel
  mode: single
- id: '1622671459948'
  alias: Regen melding
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.neerslag_buienalarm_regen_data
    above: '1'
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Het gaat regenen
      title: Regen
  mode: single
