- id: '1613302275852'
  alias: Albertheijn
  description: Locatie test
  trigger:
  - platform: zone
    entity_id: person.michel_vrauwdeunt
    zone: zone.albert_heijn_rozenburg
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Click to open the shopping list
      title: Boodschappenlijst
      data:
        clickAction: /shopping-list
        url: /shopping-list
  mode: single
- id: '1615584209554'
  alias: 3D Printer klaar met printen.
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ender_3_printing
    from: 'on'
    to: 'off'
    for: 1 seconde
  condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Printer is klaar met printen
      title: Ender 3
  mode: single
- id: '1615618158397'
  alias: Printer verbonden
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ender_3_current_state
    from: unknown
    to: Operational
  condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      title: Ender 3 staat klaar
      message: 3D printer is verbonden met OctoPrint
  mode: single
- id: '1619958186322'
  alias: Lidl
  description: Locatie test
  trigger:
  - platform: zone
    entity_id: person.michel_vrauwdeunt
    zone: zone.lidl
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: Click to open the shopping list
      title: Boodschappenlijst
      data:
        clickAction: /shopping-list
        url: /shopping-list
  mode: single
- id: '1620225024948'
  alias: test
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.grocy_shopping_list
    above: '0'
  condition: []
  action:
  - service: notify.mobile_app_oneplus_michel
    data:
      message: test
      title: test
  mode: single
