resources:
- type: module
  url: /browser_mod.js
title: Asgard
views:
- badges: []
  cards:
  - cards:
    - entities:
      - entity: person.michel_vrauwdeunt
      - entity: person.thonia
      - entity: person.zoe
      show_name: false
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n}\n\
        .card-content {\n  padding: 5\n}\n"
      theme: nest
      type: glance
    - entities:
      - cards:
        - columns: 1
          entities:
          - entity: sensor.time
          - entity: sensor.alarm_clock_time
          show_icon: false
          show_name: false
          type: glance
        type: custom:hui-vertical-stack-card
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  font-size:\
        \ 30px\n}\n.card-content {\n  padding: 0\n}\n"
      type: entities
    - entity: weather.rozenburg
      number_of_forecasts: '5'
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  position:\
        \ relative\n}\n.card-content {\n  padding: 0\n}\n"
      type: custom:weather-card
    type: vertical-stack
  - cards:
    - cards:
      - columns: 3
        entities:
        - entity: light.woonkamer
          tap_action:
            action: call-service
            service: browser_mod.popup
            service_data:
              card:
                cards:
                - cards:
                  - entity: light.spot
                    icon: mdi:spotlight-beam
                    type: light
                  - entity: light.muur
                    icon: mdi:wall-sconce-round
                    type: light
                  - entity: light.plank
                    icon: mdi:led-strip-variant
                    type: light
                  - entity: light.tafel
                    icon: mdi:ceiling-light
                    type: light
                  type: horizontal-stack
                type: custom:stack-in-card
              deviceID:
              - this
              large: false
              title: verlichting
        type: glance
      type: vertical-stack
    - artwork: cover
      entity: media_player.baldr
      hide:
        play_stop: false
        power: true
        source: true
        volume: false
      icon: mdi:kodi
      shortcuts:
        buttons:
        - icon: mdi:music
          id: shell_command.partymode
          type: service
        - icon: mdi:pine-tree
          id: Bathroom
          type: source
        columns: 3
      sound_mode: icon
      toggle_power: false
      type: custom:mini-media-player
      volume_stateless: false
    - entities:
      - entity: switch.versterker
      - entity: switch.tv_woonkamer
      type: glance
    type: vertical-stack
  - cards:
    - cards:
      - columns: 3
        entities:
        - entity: light.woonkamer
        - entity: light.spot
        - entity: light.muur
        - entity: light.plank
        - entity: light.tafel
        - entity: light.ambilight
        type: glance
      type: vertical-stack
    - dimFinishedEvents: true
      enableModeChange: true
      entities:
      - color: red
        entity: calendar.werkrooster
        icon: mdi:office
      - color: green
        entity: calendar.verjaardagen
        icon: mdi:balloon
      - color: green
        entity: calendar.feyenoord
        icon: mdi:soccer
      - entity: calendar.persoonlijk
      firstDayOfWeek: 1
      maxDaysToShow: 7
      name: Agenda
      showCurrentEventLine: false
      showDate: true
      showNoEventsForToday: true
      showRelativeTime: true
      showWeekDay: true
      type: custom:atomic-calendar-revive
    type: vertical-stack
  icon: ''
  path: home
  title: Home
- badges: []
  cards:
  - cards:
    - entities:
      - entity: person.michel_vrauwdeunt
      - entity: person.thonia
      - entity: person.zoe
      show_name: false
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n}\n\
        .card-content {\n  padding: 5\n}\n"
      theme: nest
      type: glance
    - entities:
      - cards:
        - columns: 1
          entities:
          - entity: sensor.time
          - entity: sensor.alarm_clock_time
          show_icon: false
          show_name: false
          type: glance
        type: custom:hui-vertical-stack-card
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  font-size:\
        \ 30px\n}\n.card-content {\n  padding: 0\n}\n"
      type: entities
    - entity: weather.rozenburg
      number_of_forecasts: '5'
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  position:\
        \ relative\n}\n.card-content {\n  padding: 0\n}\n"
      type: custom:weather-card
    type: vertical-stack
  - cards:
    - artwork: cover
      entity: media_player.baldr
      hide:
        play_stop: false
        power: true
        source: true
        volume: false
      icon: mdi:kodi
      shortcuts:
        buttons:
        - icon: mdi:music
          id: spotify:user:spotify:playlist:37i9dQZF1DZ06evO2O09Hg
          type: playlist
        - icon: mdi:pine-tree
          id: Bathroom
          type: source
        columns: 3
      type: custom:mini-media-player
    - cards:
      - entities:
        - entity: switch.versterker
        - entity: switch.tv_woonkamer
        type: glance
      type: vertical-stack
    type: vertical-stack
  - cards:
    - entities:
      - entity: switch.tv_slaapkamer_relay
      - entity: sensor.eettafel_override
      - entity: sensor.zithoek_override
      type: glance
    type: horizontal-stack
  icon: mdi:audio-video
  title: Media
- badges: []
  cards:
  - cards:
    - entities:
      - entity: person.michel_vrauwdeunt
      - entity: person.thonia
      - entity: person.zoe
      show_name: false
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n}\n\
        .card-content {\n  padding: 5\n}\n"
      theme: nest
      type: glance
    - entities:
      - cards:
        - columns: 1
          entities:
          - entity: sensor.time
          - entity: sensor.alarm_clock_time
          show_icon: false
          show_name: false
          type: glance
        type: custom:hui-vertical-stack-card
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  font-size:\
        \ 30px\n}\n.card-content {\n  padding: 0\n}\n"
      type: entities
    - entity: weather.rozenburg
      number_of_forecasts: '5'
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  position:\
        \ relative\n}\n.card-content {\n  padding: 0\n}\n"
      type: custom:weather-card
    type: vertical-stack
  - cards:
    - entities:
      - entity: switch.adaptive_lighting_zithoek
        name: Zithoek
      - entity: switch.adaptive_lighting_sleep_mode_zithoek
        name: Slaapstand
      - entity: sensor.woonkamer_illuminance
      - entity: switch.adaptive_lighting_eettafel_2
        name: Eettafel
      - entity: switch.adaptive_lighting_sleep_mode_eettafel
        name: Slaapstand
      type: glance
    - columns: 3
      entities:
      - entity: light.spot
      - entity: light.muur
      - entity: light.plank
      - entity: light.tafel
      title: Woonkamer
      type: glance
    type: vertical-stack
  - entities:
    - entity: light.hal
    - entity: binary_sensor.hal_schakelaar
    - entity: light.hal_relais
    title: Hal
    type: glance
  - entities:
    - entity: switch.adaptive_lighting_adapt_brightness_zithoek
    - entity: switch.adaptive_lighting_adapt_brightness_eettafel
    - entity: switch.adaptive_lighting_adapt_color_zithoek
    - entity: switch.adaptive_lighting_adapt_color_eettafel
    type: glance
  icon: mdi:lightbulb-group
  path: lights
  title: lights
- badges: []
  cards:
  - cards:
    - entities:
      - entity: person.michel_vrauwdeunt
      - entity: person.thonia
      - entity: person.zoe
      show_name: false
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n}\n\
        .card-content {\n  padding: 5\n}\n"
      theme: nest
      type: glance
    - entities:
      - cards:
        - columns: 1
          entities:
          - entity: sensor.time
          - entity: sensor.alarm_clock_time
          show_icon: false
          show_name: false
          type: glance
        type: custom:hui-vertical-stack-card
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  font-size:\
        \ 30px\n}\n.card-content {\n  padding: 0\n}\n"
      type: entities
    - details: true
      entity: weather.rozenburg
      hourly_forecast: false
      number_of_forecasts: '5'
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  position:\
        \ relative\n}\n.card-content {\n  padding: 0\n}\n"
      type: custom:weather-card
    type: vertical-stack
  - cards:
    - entities:
      - entity: weather.rozenburg
      - entity: sensor.season
        name: Seizoen
      - entity: sensor.neerslag_buienalarm_regen_data
        name: Neerslag
      type: glance
    - entity: camera.buienradar_loop
      show_name: false
      show_state: false
      type: picture-entity
    type: vertical-stack
  - cards:
    - cards:
      - columns: 3
        entities:
        - entity: sensor.rotterdam_feel_temperature
          name: Temperatuur
        - entity: sensor.rotterdam_symbol
          name: Conditie
        - entity: sensor.rotterdam_humidity
          name: Luchtvochtigheid
        - entity: sensor.rotterdam_precipitation_forecast_average
          name: Neerslag
        - entity: sensor.rotterdam_wind_direction
          name: Windrichting
        - entity: sensor.rotterdam_wind_speed
          name: Windsnelheid
        type: glance
      type: vertical-stack
    - entities:
      - sensor.neerslag_buienalarm_regen_data
      - sensor.neerslag_buienradar_regen_data
      title: Neerslag
      type: custom:neerslag-card
    type: vertical-stack
  icon: mdi:cloud
  path: weer
  title: Weer
- badges: []
  cards:
  - cards:
    - entities:
      - entity: person.michel_vrauwdeunt
      - entity: person.thonia
      - entity: person.zoe
      show_name: false
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n}\n\
        .card-content {\n  padding: 5\n}\n"
      theme: nest
      type: glance
    - entities:
      - cards:
        - columns: 1
          entities:
          - entity: sensor.time
          - entity: sensor.alarm_clock_time
          show_icon: false
          show_name: false
          type: glance
        type: custom:hui-vertical-stack-card
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  font-size:\
        \ 30px\n}\n.card-content {\n  padding: 0\n}\n"
      type: entities
    - details: true
      entity: weather.rozenburg
      hourly_forecast: false
      number_of_forecasts: '5'
      style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
        \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n  position:\
        \ relative\n}\n.card-content {\n  padding: 0\n}\n"
      type: custom:weather-card
    type: vertical-stack
  - cards:
    - cards:
      - columns: 3
        entities:
        - entity: sensor.kelder_3d_printer_uptime
        - entity: sensor.ender_3_current_state
        - entity: binary_sensor.ender_3_printing
        type: glance
      type: vertical-stack
    - cards:
      - entity: sensor.ender_3_actual_tool0_temp
        max: 250
        min: 0
        name: Nozzle
        type: gauge
      - entity: sensor.ender_3_actual_bed_temp
        max: 100
        min: 0
        name: Bed
        type: gauge
      type: horizontal-stack
    - entities:
      - entity: switch.3d_printer_relais
        name: stroomschakelaar
      type: glance
    type: vertical-stack
  icon: mdi:printer-3d
- badges: []
  cards:
  - entities:
    - entity: sensor.system_uptime
      icon: mdi:desktop-classic
      secondary_info: 'Since: [[ sensor.last_boot_date_time ]]'
      type: custom:secondaryinfo-entity-row
    - entity: sensor.uptime
      icon: mdi:home-assistant
    - entities:
      - entity: sensor.homeassistant_git_version
        name: Latest
      entity: sensor.current_version
      icon: mdi:home-assistant
      name: HA Installed Version
      state_header: Current
      style: ":host {\n  {% if states(config.entity).split('.')[1] != states('sensor.homeassistant_git_version').split('.')[1]\
        \ %}\n    color: rgb(255, 165, 0);\n    --paper-item-icon-color: rgb(255,\
        \ 165, 0);\n  {% endif %};\n}\n"
      type: custom:multiple-entity-row
    - entity: sensor.hacs
      name: HACS
      style: ":host {\n  {% if states(config.entity) != '0' %}\n    color: rgb(255,\
        \ 165, 0);\n    --paper-item-icon-color: rgb(255, 165, 0);\n  {% endif %};\n\
        }\n"
      tap_action:
        action: navigate
        navigation_path: /hacs/entry
    - entity: sensor.home_assistant_log
      style: ":host {\n  {% if states(config.entity) >= '0.5' %}\n    color: rgb(255,\
        \ 165, 0);\n    --paper-item-icon-color: rgb(255, 165, 0);\n  {% endif %};\n\
        }\n"
      tap_action:
        action: url
        url_path: http://192.168.178.250:8123/developer-tools/logs
    - entity: sensor.home_assistant_v2_db
      icon: mdi:database
    - entity: sensor.nuc_model
      icon: mdi:desktop-classic
      secondary_info: 'Board Name: [[ sensor.nuc_board_name ]]'
      type: custom:secondaryinfo-entity-row
    - entity: sensor.bios_vendor
      icon: mdi:desktop-classic
      secondary_info: 'Version: [[ sensor.nuc_bios_version ]]'
      type: custom:secondaryinfo-entity-row
    - columns: 2
      entities:
      - entity: sensor.processor_use
        icon: mdi:chip
        name: CPU
      - entity: sensor.memory_use_percent
        icon: mdi:memory
        name: RAM
      - entity: sensor.cpu_temperature
        icon: mdi:thermometer
        name: Temp
      - entity: sensor.disk_use_percent
        icon: mdi:harddisk
        name: Disk
      positions:
        indicator: 'off'
      severity:
      - color: green
        from: 0
        to: 60
      - color: orange
        from: 61
        to: 80
      - color: red
        from: 81
        to: 100
      style: "bar-card-title {\n  text-shadow: 1px 1px 5px black;\n}\nbar-card-value\
        \ {\n  text-shadow: 1px 1px 5px black;\n} "
      type: custom:bar-card
    show_header_toggle: false
    type: entities
  - entities:
    - entity: binary_sensor.woonkamer_pir_sensor
    - entity: sensor.woonkamer_temperatuur
    - entity: sensor.woonkamer_luchtvochtigheid
    type: glance
  - entities:
    - entity: sensor.esphome_git_version
    - entity: binary_sensor.woonkamer_pir_sensor
    - entity: sensor.woonkamer_temperatuur
    - entity: sensor.woonkamer_temperatuur
    - entity: sensor.woonkamer_wifi_signal
    - entity: sensor.woonkamer_uptime
    - entity: sensor.woonkamer_illuminance
    type: entities
  path: systeem
  title: Systeem
- badges: []
  cards:
  - cards:
    - cards:
      - columns: 5
        entities:
        - entity: sensor.docker_deconz_state
          name: Deconz
        - entity: sensor.docker_esphome_state
          name: ESPHome
        - entity: sensor.docker_grafana_state
          name: Grafana
        - entity: sensor.docker_influxdb_state
          name: InfluxDB
        - entity: sensor.docker_mqtt_state
          name: MQTT
        title: Smarthome Docker containers
        type: glance
      - columns: 5
        entities:
        - entity: sensor.docker_airsonic_state
          name: Airsonic
        - entity: sensor.docker_hydra_state
          name: Hydra
        - entity: sensor.docker_jellyfin_state
          name: Jellyfin
        - entity: sensor.docker_lidarr_state
          name: lidarr
        - entity: sensor.docker_radarr_state
          name: Radarr
        - entity: sensor.docker_sabnzbd_state
          name: SabNZBd
        - entity: sensor.docker_sonarr_state
          name: Sonarr
        - entity: sensor.docker_spotweb_state
          name: Spotweb
        - entity: sensor.docker_transmission_state
          name: Transmission
        title: Media Docker containers
        type: glance
      type: vertical-stack
    type: vertical-stack
  icon: mdi:docker
  path: docker
  title: Docker
- badges: []
  cards:
  - entities:
    - entity: person.michel_vrauwdeunt
    - entity: sensor.woonkamer_temperatuur
    - entity: person.thonia
    show_name: false
    theme: nest
    type: glance
  - title: Boodschappen
    type: shopping-list
  - entities:
    - entity: sensor.alarm_clock_time
    - entity: switch.kodi_party_mode
    type: glance
  - entity: media_player.wallpanel
    type: media-control
  - entity: sensor.time
    from: bottom
    max: 100
    min: 0
    scale: 30px
    style: "ha-card {\n  --ha-card-background: transparant;\n  --ha-card-box-shadow:\
      \ 'inset 0px 0px 0px 0px';\n  box-shadow: none;\n  background: none;\n}\n.card-content\
      \ {\n  padding: 5\n}\n"
    theme: nest
    title: null
    type: custom:bignumber-card
  - entities:
    - entity: weather.rozenburg
    - entity: sensor.date_time
    - entity: sensor.date_time_utc
    type: glance
  - entities:
    - sensor.grocy_chores
    - binary_sensor.grocy_expired_products
    - binary_sensor.grocy_expiring_products
    - sensor.grocy_meal_plan
    - binary_sensor.grocy_missing_products
    - binary_sensor.grocy_overdue_chores
    - binary_sensor.grocy_overdue_tasks
    - sensor.grocy_shopping_list
    - sensor.grocy_stock
    - sensor.grocy_tasks
    type: entities
  path: test
  title: test
