id: d5fe6c66-a645-445e-b98d-206bb743b98c
alias: MiLight Forwarder
initial_state: True
trigger:
  platform: mqtt
  topic: milight/updates/2294/rgb_cct/+
action:
  - service: mqtt.publish
    data_template:
      topic: "milight/commands/2294/rgb_cct/{{ trigger.topic.split('/')[4] }}"
      payload_template: >
        {{ trigger.payload }} 
