id: ca65dc5b-c5aa-46d2-8f74-b73ab47d8733
alias: "ambilight Off"
initial_state: 'on'
trigger:
  - platform: state
    entity_id: light.woonkamer
    to: 'off'
  - platform: mqtt
    topic: 'milight/updates/0x2294/rgb_cct/0'
    payload: '{"state":"OFF"}'
  - platform: state
    entity_id: switch.tv_woonkamer
    to: 'off'
  - platform: state
    entity_id: switch.sleeping
    to: 'on'

action:
  - service: light.turn_off
    data:
      entity_id: light.ambilight 
