---
alias: "Turn automatics lights off"
trigger:
  - platform: state
    entity_id: light.woonkamer
    from:  "on"
    to:  "off"

action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.automatic_lights
