alias: "Woonkamer Lights On"
#initial_state: 'on'

trigger:
  - platform: numeric_state
    entity_id: sensor.woonkamer_illuminance
    below: 15

  - platform: state
    entity_id: group.tracked_people
    from: "not_home"
    # Optional
    to: "home"

  - platform: state
    entity_id: switch.sleeping
    to: 'off'

condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.woonkamer_illuminance
    below: 20
  - condition: state
    entity_id: group.tracked_people
    state: home

action:
  ### set the boolean on. To let HA know that the lights the lights have been turned on automatically
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.automatic_lights
  ### slowly turn on the lights to the state of circadian

  - service: light.turn_on
    data:
      entity_id: 
        - light.muur
        - light.spot
        - light.tafel
      transition: 10

  - service: light.turn_on
    data:
      entity_id: 
        - light.plank
      transition: 10