alias: "Woonkamer Lights Off"
#initial_state: 'on'
trigger:
  - platform: numeric_state
    entity_id: sensor.woonkamer_illuminance
    above: 20

condition:
  condition: state
  entity_id: input_boolean.automatic_lights
  state: 'on'

action:
  ### Turn of The Ambilight
  - service: light.turn_off
    data:
      entity_id: light.ambilight
  - service: light.turn_off
    data:
      transition: 5
      entity_id:
      - light.muur
      - light.spot
      - light.plank
      - light.tafel