id: 3dddc97e-47e8-426c-a051-7fe14a3e6c59
alias: "Media player Stopped"
initial_state: 'on'
trigger:
  platform: state
  entity_id: media_player.baldr
  to: 'idle'
  for:
    minutes: 5
action:
  - service: switch.turn_off
    data:
      entity_id: switch.versterker
