---
id: 2dec9601-a7a3-4125-badf-f3cde1dd33c5
  # Turn on the amplifier when playing media
alias: "Media player playing"
initial_state: on
trigger:
  platform: state
  entity_id: media_player.baldr
  to: 'playing'

action:
  service: switch.turn_on
  data:
    entity_id: switch.versterker