trigger:
  - platform: state
    entity_id: group.tracked_people
    from: "not_home"
    # Optional
    to: "home"

  - platform: state
    entity_id: switch.sleeping
    to: 'off'
    for: "00:30:00"

condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  - condition: state
    entity_id: group.tracked_people
    state: home

action:
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      entity_id: climate.woonkamer
