trigger:
  - platform: state
    entity_id: group.tracked_people
    from: "home"
    # Optional
    to: "not_home"

  - platform: state
    entity_id: switch.sleeping
    to: 'on'

condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'on'
  - condition: state
    entity_id: group.tracked_people
    state: not_home

action:
  - service: climate.set_temperature
    data:
      temperature: 10
    target:
      entity_id: climate.woonkamer
