alias: "hal Lights On"
#initial_state: 'on'

trigger:
  - platform: numeric_state
    entity_id: sensor.woonkamer_illuminance
    below: 15

  - platform: state
    entity_id: group.tracked_people
    from: "not_home"
    # Optional
    to: "home"

  - platform: state
    entity_id: switch.sleeping
    to: 'off'

condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.woonkamer_illuminance
    below: 20
  - condition: state
    entity_id: group.tracked_people
    state: home

action:
  ### slowly turn on the lights to the state of circadian

  - service: light.turn_on
    data:
      entity_id: 
        - light.hal
      transition: 10