trigger:
  platform: event
  event_type: esphome.button_pressed
  event_data: 
    title: shelly Hal toggle

action:
  - service: light.toggle
    data:
      entity_id: 
        - light.hal
      brightness_pct: 15