id: 9d9709cc-568d-49a2-8ae8-50f8f5f1f10d
alias: "hal Lights Off"
#initial_state: 'on'
trigger:
  - platform: numeric_state
    entity_id: sensor.woonkamer_illuminance
    above: 20

condition:
  condition: state
  entity_id: input_boolean.automatic_lights
  state: 'on'

action:
  - service: light.turn_off
    data:
      transition: 5
      entity_id:
      - light.hal