alias: "add to shopping list"
trigger:
  platform: event
  event_type: rhasspy_HassShoppinglistAdd
  event_data: {}
  #   name: 'bedroom light'
  #   color: 'blue'
action:
  service: shopping_list.add_item
  data_template:
    name: "{{ trigger.event.data.item | string }}"