alias: "remove to shopping list"
trigger:
  platform: event
  event_type: rhasspy_HassShoppinglistRemove
  event_data: {}
  #   name: 'bedroom light'
  #   color: 'blue'
action:
  service: shopping_list.complete_item
  data_template:
    name: "{{ trigger.event.data.item | string }}"