  # Time to wake up
id: fdb3ec75-5681-4ee2-9c8b-34969314e384
alias: Wakeup Time
initial_state: 'on'
trigger:
  platform: template
  value_template: '{{ states.sensor.time.state == states.sensor.alarm_clock_time.state }}'

action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.sleeping
  - service: switch.turn_off
    data:
      entity_id:
        - switch.adaptive_lighting_sleep_mode_zithoek
        - switch.adaptive_lighting_sleep_mode_eettafel
  - service: light.turn_on
    data:
      entity_id: light.wallpanel