id: '1620376964212'
alias: Bedtime
description: Going to bed
trigger:
  - platform: state
    entity_id: switch.sleeping
    to: 'on'

condition: []

action:

  - service: switch.turn_on
    target:
      entity_id:
        - switch.adaptive_lighting_sleep_mode_zithoek
        - switch.adaptive_lighting_sleep_mode_eettafel

  - service: media_player.volume_set
    target:
      entity_id: media_player.wallpanel
    data:
      volume_level: 0.5

  - service: notify.wallpanel
    data_template:
      message: !include ../../../../announcements/goodnight.yaml

  # - service: switch.turn_off
  #   target:
  #     entity_id: 
  #       - switch.tv_woonkamer

  - service: media_player.turn_off
    target:
      entity_id:
        - media_player.denon_avr_x1600h

  - service: light.turn_off
    target:
      entity_id: 
        - light.ambilight
        - light.plank
        - light.wallpanel

  - delay:
      seconds: 20
        # - switch.tv_slaapkamer

  - service: light.turn_off
    data:
        transition: 10
    target:
        entity_id:
        - light.hal
        - light.spot
        - light.muur_1
        - light.muur_2
        - light.tafel_1
        - light.tafel_2

mode: single