id: '1620376964212'
alias: Bedtime
description: Going to bed
trigger:
  - platform: state
    entity_id: switch.sleeping
    to: 'on'

condition: []

action:
  # - service: notify.mobile_app_oneplus_michel
  #   data:
  #       message: Have a good nights sleep. Turning the lights and PC off
  #       title: Good night
  - service: switch.turn_on
    target:
      entity_id:
        - switch.adaptive_lighting_sleep_mode_zithoek
        - switch.adaptive_lighting_sleep_mode_eettafel

  - service: media_player.volume_set
    target:
        device_id: cd163c421cb588be2d1fdfd3ba9259e7
    data:
        volume_level: 0.25

  - service: notify.wallpanel
    data_template:
      message: !include ../../../../announcements/goodnight.yaml

  - service: switch.turn_off
    target:
      entity_id: 
        - switch.tv_woonkamer

  - service: media_player.turn_off
    target:
      entity_id:
        - media_player.denon_avr_x1600h

  - service: light.turn_off
    target:
      entity_id: 
        - light.ambilight
        - light.plank

        # - switch.tv_slaapkamer
  - delay:
      seconds: 2

  - service: light.turn_off
    data:
        transition: 10
    target:
        entity_id:
        - light.hal
        - light.spot
        - light.muur
        - light.muur_1
        - light.muur_2
        - light.tafel
        - light.tafel_1
        - light.tafel_2
        - light.browser_mod_acede475_ddae5a6b

mode: single