id: '1620376964212'
alias: Bedtime
description: Going to bed
trigger:
  - platform: state
    entity_id: switch.sleeping
    to: 'on'

condition: []

action:
  - service: notify.mobile_app_oneplus_michel
    data:
        message: Have a good nights sleep. Turning the lights and PC off
        title: Good night

  - service: media_player.volume_set
    target:
        device_id: cd163c421cb588be2d1fdfd3ba9259e7
    data:
        volume_level: 0.20

  - service: notify.wallpanel
    data_template:
      message: !include ../../../../announcements/goodnight.yaml

  - service: light.turn_off
    target:
        entity_id: light.ambilight
        
  - service: light.turn_off
    target:
        entity_id:
        - light.hal
        - light.plank
    data:
        transition: 5

  # - service: switch.turn_off
  #   target:
  #       entity_id:
  #       - switch.adaptive_lighting_zithoek
  #       - switch.adaptive_lighting_eettafel

  - service: switch.turn_on
    target:
        entity_id:
        - switch.adaptive_lighting_sleep_mode_zithoek
        - switch.adaptive_lighting_sleep_mode_eettafel

  - delay:
      minutes: 10

  - service: light.turn_off
    data:
        transition: 5
    target:
        entity_id:
        - light.spot
        - light.muur
        - light.tafel
mode: single