id: '1620376964212'
alias: Bedtime
description: Going to bed
trigger:
  - platform: state
    entity_id: switch.sleeping
    to: 'on'

condition: []

action:
  # - service: notify.mobile_app_oneplus_michel
  #   data:
  #       message: Have a good nights sleep. Turning the lights and PC off
  #       title: Good night

  - service: media_player.volume_set
    target:
        device_id: cd163c421cb588be2d1fdfd3ba9259e7
    data:
        volume_level: 0.25

  - service: notify.wallpanel
    data_template:
      message: !include ../../../../announcements/goodnight.yaml

  - service: light.turn_off
    target:
      entity_id: 
        - light.ambilight
        - light.plank
  - service: light.turn_off
    target:
      entity_id:
        - light.hal
    data:
      transition: 5
  - service: switch.turn_on
    target:
      entity_id:
        - switch.adaptive_lighting_sleep_mode_zithoek
        - switch.adaptive_lighting_sleep_mode_eettafel
        # - switch.tv_slaapkamer
  # - delay:
  #     minutes: 5

  - service: light.turn_off
    data:
        transition: 30
    target:
        entity_id:
        - light.spot
        - light.muur_1
        # - light.muur_1
        # - light.muur_2
        - light.tafel
        # - light.tafel_1
        # - light.tafel_2
mode: single