  # When sleeping, play a good night TTS message, turn off
  # all lighting, turn on stair nightlight lighting, turn off
  # smart sockets, pause media, and lock the front door.
  # If any door is open, don't activate.
  # If temperature meets a threshold, turn on the bedroom fan.
alias: Sleeping
initial_state: 'on'
trigger:
  - platform: state
    entity_id: switch.sleeping
    to: 'on'

  # - condition: state
  #   entity_id: switch.guests
  #   state: 'off'

action:
  - service: notify.notify
    data:
      title: "Good night"
      message: "Have a good nights sleep. Turning the lights and PC off"
  - service: media_player.volume_set
    data:
      volume_level: 0.22
      entity_id: media_player.wallpanel

  - service: notify.wallpanel
    data:
      message: "Slaaplekker."
#  - service: switch.turn_on
#    data:
#    entity_id: switch.freya

## turning living room lights off

  # - service: light.turn_off
  #   data:
  #     transition: 5
  #     entity_id: 
  #       - light.muur
  #       - light.spot
  #       - light.plank
  #       - light.tafel    
  - service: light.turn_off
    data:
      entity_id: light.ambilight

## Wait a couple off seconds before activating the MiLight Night-mode effect 
  # - delay: 
  #     seconds: 5
  - service: scene.turn_on
    data:
      entity_id: scene.woonkamer_nightmode_2
      transition: 5
#  - wait_template: "{{ not is_state('media_player.freya', 'off') }}"
#  - service: media_player.play_media
#    data:
#    entity_id: media_player.freya
#    media_content_type: audio/mp4
#    data_template:
#    media_content_id: >
#    {{ ["smb://freya/Music/Nature/Birds/Birds Singing.mp3", "smb://freya/Music/Nature/Birds/Forest and Nature.mp3", "smb://freya/Music/Nature/Birds/Forest Birds Singing.mp3" ] | random }}
  # - service: switch.turn_off
  #   data:
  #     entity_id: switch.desktop_odin

  ## Wait 10 minutes before turning off all the lights
  - delay:
      minutes: 10

  - service: light.turn_off
    data:
      entity_id: 
        - light.muur
        - light.spot
        - light.plank
        - light.tafel
      transition: 5