id: 6539f7e4-7b3b-4936-acec-68da0e2e342f
alias: Turn off sleep mode automatically
initial_state: 'on'
trigger:
  platform: time
  at: '10:00:00'
condition:
  - condition: state
    entity_id: switch.sleeping
    state: 'on'
action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.sleeping
  - service: light.turn_on
    target:
      entity_id: light.browser_mod_acede475_ddae5a6b
